### PR TITLE
remove lets encrypt dependency

### PR DESCRIPTION
**Pull request by sadnub**
modified install.sh to make Let's Encrypt option. If opted out, it will create a self signed certificate so https works. I tested and it looks good. You may want to run through the script once to make sure it is good with your setup.

### CODE REVIEW

**Comment by mmaridev** [comment]
May I ask why the modification to allow non-certbot certificate introduced with this MR is not in develop? How should one do that?

**Comment by wh1te909** [comment]
@mmaridev https://wh1te909.github.io/tacticalrmm/unsupported_scripts/#using-purchased-ssl-certs-instead-of-letsencrypt-wildcards

self signed will not work make sure it's a real cert

**Comment by dinger1986** [comment]
The script is in progress, I am hoping to finish it over the holidays with the options for txt let's encrypt wildcard, http let's encrypt and also using your own wildcard cert but not self signed as won't work.

**Comment by mmaridev** [comment]
ok fine. What about internal PKI? I have also a private ACME that could be used. I should propagate the CA to all the clients, I swear. Anything else?

**Comment by silversword411** [comment]
> What about internal PKI?

We use nats for a light-fast method of agent to server communication. Can you see what https://nats.io has to say in terms of internal PKI?

For simplicity in support, we officially recommend using publicly verifiable certs. If you can create a PR with internal PKI support the devs will definitely look at it, thanks!

**Comment by casaresjm** [comment]
> For simplicity in support, we officially recommend using publicly verifiable certs. If you can create a PR with internal PKI support the devs will definitely look at it, thanks!
So we can use, let's say, GoDaddy Wildcard certs? I did not see any documentation on that. Can you point me to?

**Comment by dinger1986** [comment]
@casaresjm https://docs.tacticalrmm.com/functions/settings_override/#using-your-own-wildcard-ssl-cert

**Comment by casaresjm** [comment]
Thank you, @dinger1986 I didn't find it in Google or the documentation site in the places I searched.

**Pull request merged**
