### PR TITLE
Add in Client and Site variables

### PR DESCRIPTION
**Pull request by davidrudduck**
Allows for passing -client {{client.name} -site {{site.name}} to the script so these values will pass into ScreenConnect.

### CODE REVIEW

**Comment by wh1te909** [comment]
pinging @bradhawkins85 since he is author of this, not sure if these changes will break existing functionality. if so i think we should make these args optional

**Comment by davidrudduck** [comment]
In most cases, the URL for ScreenConnect has &t=&c=&c=&c=&c=&c=&c= in it (all blank values) and this just changes it so the first and second &c= after the &t= contains client name and site name.

It might affect existing grouping rules as ConnectWise Automate by default likes not having any spaces between the words in a name (ie: Insane Technologies is written InsaneTechnologies). But that could be modified in the script to strip spaces and nulls?

**Comment by bradhawkins85** [comment]
Adding &c=$company&c=$site to the end of the download URL will essentially make the URL Access&y=Guest&t=&c=&c=&c=&c=&c=&c=&c=&c=&c=$company&c=$site
Which will likely cause issues.

I am happy to modify the script to include the Company and Site it will need some processing to find and replace the correct &c= with the variables. Spaces should be easy enough to handle (replace with %20)

**Comment by davidrudduck** [comment]
In my URL i cut everything out after the &t= and added in the &c=CompanyName&c=SiteName parts (without further &c= variables).

It would just require instruction to the user to cut off everything after &t= (or you'd have to code it to do that yourself)

**Comment by bradhawkins85** [comment]
I'd rather add it to the code, the fewer instructions needed the better.

**Comment by davidrudduck** [comment]
> I'd rather add it to the code, the fewer instructions needed the better.

That's fair enough. Makes it seamless as well.

> I am happy to modify the script to include the Company and Site it will need some processing to find and replace the correct &c= with the variables. Spaces should be easy enough to handle (replace with %20)

I more more meant that we may wish to consider STRIPPING (not replacing) spaces; particularly for those people who may be coming from CWA or who may still be actively using the two platforms. Assuming they name Company and Location/Sites the same as they are doing in their incumbent RMM.

**Comment by bradhawkins85** [comment]
I'm not sure how CWA works from this perspective, can you please provide some clarification it's been a long time since I've had to use CWA.

Is the site names Insane Technologies in CWA but ScreenConnect changes this to InsaneTechnologies or are you naming the client InsaneTechnologies in CWA which is also in ScreenConnect.

Again I think it's best to stick to the default of pulling the site name from TRMM and using it directly for anyone else not coming from CWA. Maybe, down the track I can add ScreeenConnectStripSpaces variable True/False but will start with just the default for now.

@wh1te909 should we add as a feature request?

**Comment by davidrudduck** [comment]
> I'm not sure how CWA works from this perspective, can you please provide some clarification it's been a long time since I've had to use CWA.
> Is the site names Insane Technologies in CWA but ScreenConnect changes this to InsaneTechnologies or are you naming the client InsaneTechnologies in CWA which is also in ScreenConnect.

Disregard this. I got confused. I think possibly in earlier versions (LabTech days) it may have required no spaces in names; but I've just tested in our CWA instance and it doesn't care whether we name someone "Insane Technologies" or "InsaneTechnologies".
 
> Again I think it's best to stick to the default of pulling the site name from TRMM and using it directly for anyone else not coming from CWA. Maybe, down the track I can add ScreeenConnectStripSpaces variable True/False but will start with just the default for now.

Don't worry about this.

**Pull request merged**
