### PR TITLE
Policy Tasks with fixes and docker changes

### PR DESCRIPTION
**Pull request by sadnub**
Here are the policy tasks. I also fixed some bugs and changed around some of the docker setup.

With the tasks, I noticed that if I assign the same check to multiple tasks it will error out. Not sure if a check should only be assigned to one task or if multiple should be allowed.

Let me know fi you want me to change anything!

### CODE REVIEW

**Comment by wh1te909** [comment]
Thank you! Checking the multiple tasks now

**Comment by wh1te909** [comment]
Havent checked tasks yet but was testing docker and api container still fails to start, but fixed by changing the sleep in api/prestart.sh from 10 seconds to 120 (probably overkill but can't really predict how long meshcentral will take to install it's plugins during the first start, obv will take less time on faster hardware). I thought by building mesh first would solve but didn't realize it doesn't actually run during the build sorry I am still new to docker lol.

**Comment by sadnub** [comment]
I was doing a little research and there isn't an easy way to handle this. I was thinking of this more and we could have the API container wait until it sees the key file and save it. Or have mesh central container hit an API endpoint and save the key when it is to that point. Could use curl as the http client and put a line in the entry.sh file.

**Comment by wh1te909** [comment]
hmm first option seems easier I think? Something like an infinite while True loop and then only break one file exists

**Pull request merged**
