### PR TITLE
added a Connectwise Control Integration document.

### PR DESCRIPTION
**Pull request by meuchels**
I am really new to git so let me know if this works or is the right way to do this.

### CODE REVIEW

**Comment by silversword411** [comment]
Looks good, thanks for submission! 

I've been trying to think thru how long-term the docs should be arranged considering there's a lot of 3rd part technologies that can all have their own Tips/Howto's. I was trying to balance many pages vs one big page and then how a tipsntricks page, and a Getting Started Guide would integrate with those

Once @wh1te909 integrates I'm probably going to re-arrange this into it's own section: 3rd Party Integrations
Then we'll have: Screenconnect, Teamviewer, Anydesk, Bitdefender, etc with all of their own pages.

**Comment by Omnicef** [comment]
There is a couple of minor issues that need to be fixed on that doc. Not sure how I can fix it...
the url sample is missing a { around agent.ScreenConnectGuid and if you copy and paste the ScreenconnectGUID field as you follow along... the url also needs the agent.ScreenConnectGuid to be changed to agent.ScreenConnectGUID so it will match and then work.

Other than that, it was an awesome guide and wprked well!

**Comment by silversword411** [comment]
> the url sample is missing a { around agent.ScreenConnectGuid 

Fixed that last night I thought

> and if you copy and paste the ScreenconnectGUID field as you follow along... the url also needs the agent.ScreenConnectGuid to be changed to agent.ScreenConnectGUID so it will match and then work.

Just fixed :)

**Comment by meuchels** [comment]
I thought when I was originally writing it that I was catching all the case sensitivity.
Apparently not :)
Thanks for correcting.

**Pull request merged**
