### PR TITLE
2 script updates, one removal

### PR DESCRIPTION
**Pull request by silversword411**
Smaller bits

### CODE REVIEW

**Comment by silversword411** [comment]
Event viewer - check for blue screens is failing? Didn't touch that in this commit.

**Comment by wh1te909** [comment]
no, scroll up to see exactly where it's failing don't look at the bottom. that's just the last script

```
FAIL: test_community_script_json_file (scripts.tests.TestScriptViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/myagent/_work/1/s/api/tacticalrmm/scripts/tests.py", line 206, in test_community_script_json_file
    self.assertTrue(os.path.exists(os.path.join(scripts_dir, fn)))
AssertionError: False is not true

======================================================================
FAIL: test_load_community_scripts (scripts.tests.TestScriptViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/myagent/_work/1/s/api/tacticalrmm/scripts/tests.py", line 229, in test_load_community_scripts
    self.assertEqual(len(info), community_scripts)
AssertionError: 35 != 33
```

**Comment by silversword411** [comment]
Oh, I thought the last thing it processed was the error. Seemed to be with that last disastrous commit. 

So that's nothing I can fix right? Don't even know what it means. Is that the total count of scripts? Should I be updating a count somewhere when I add/remove scripts?

**Comment by wh1te909** [comment]
the `filename` in `community_scripts.json` has to match the actual file name on disk that's in the `scripts` folder in the root of the project that's where the first test is failing. you renamed the file only in the json file, but didn't rename it also on disk. 

therefore those 2 scripts were not added to the database which is why that 2nd check fails cuz there if there are 35 entries in community_scripts.json there should also be 35 database entries, but there are only 33 cuz 2 of them failed to load.

so just rename the 2 files on disk and then checks should pass

**Comment by silversword411** [comment]
...after blowing away my fork, the commit and push doesn't seem to be following thru. Still had uncommited changes in vscode that weren't pushing to github :(

I hope it's fixed now.

**Comment by wh1te909** [comment]
lmao i feel your pain. ya looks good now ty :)

**Pull request merged**
