### PR TITLE
Automation and Alerts Overview

### PR DESCRIPTION
**Pull request by sadnub**
Here is what I have so far policy based checks and alerts overview.

I am thinking of reusing the ChecksTab component for the Automation Manager UI. Currently this component and the modals are tightly coupled to the agent. I was thinking of creating a generic object that is passed with a type and perform saves/edits to the correct endpoint based on the type. Not sure yet on that still working through it

After that is working I just need to create some tasks that will check policies and run the checks on the affected endpoints.

I should have something working this month. Let me know if you need me to change anything

### CODE REVIEW

**Comment by sadnub** [comment]
Do you have any preferences on tests for vue or python? I was thinking about creating some for the components I am modifying.

**Comment by wh1te909** [comment]
Looks good, thank you!
I actually had already started working on a "Tasks" tab right before you submitted this PR, which yes is very similar to the ChecksTab and can be linked to a check, so when creating a check there will be an option to run a task on check failure. Here is what it will look like (taken from our current rmm):

checkstab1


taskstab1

I'm going to merge this PR and then add the work I've done so far for the tasks, hopefully it's similar to what you had in mind. The tasks are still only applied to an agent or a specific check, so it should be able to integrate nicely with the global policies and alerts code you are working on.

For django tests I've just been using the standard unittest framework that django recommends:
https://docs.djangoproject.com/en/3.0/topics/testing/overview/
I am using the pytest framework for the windows agent, don't really have a preference though.

I've never written Vue (or any javascript) tests so use whatever you want and I'll just see how you do it and prolly start writing for some components as well :)

**Comment by sadnub** [comment]
Thanks for the feedback! 

I hope my WIP PR doesn't break anything :)

What I could do is allow for Checks and Tasks to be added to a Policy.

Then whenever Checks or Tasks are enumerated for an agent I can do the following:

- Check if the agent Client has any policies applied and include those checks and tasks
- Check if the agent Site has any policies applied and include those checks and tasks
- Check if the agent has any policies applied and include those checks and tasks

When the Policy checks and tasks are added to the system, it will create tasks and checks in their tables, but will have a policy_id set. I don't think the agent_id can be null, so I can use either a dummy agent_id {00000000-0000-0000-0000-000000000005} or set it to accept null values. 

I haven't done too much with the alerts accept for creating some of the UI.

I should have some time to work on this over the next few weeks. Awesome work so far on this!

**Comment by sadnub** [comment]
Also, I have been just rebasing my feature branches anytime you update you develop branch, so I am working off of the latest changes. 

I'm not sure if my code broke the summary tab or not. I had to rework the salt container and I have that working now, but the wmi_detail module doesn't seem to be pulling any information. I ran the module manually on the agent and it is working. Maybe the return data is too large? I have the max_size set in the salt config. Or maybe this is a known issue? Other tasks are working so i wasn't sure. I have no experience with salt, but I'm learning!

**Comment by wh1te909** [comment]
> Thanks for the feedback!
> 
> I hope my WIP PR doesn't break anything :)
> 
> What I could do is allow for Checks and Tasks to be added to a Policy.
> 
> Then whenever Checks or Tasks are enumerated for an agent I can do the following:
> 
> * Check if the agent Client has any policies applied and include those checks and tasks
> * Check if the agent Site has any policies applied and include those checks and tasks
> * Check if the agent has any policies applied and include those checks and tasks
> 
> When the Policy checks and tasks are added to the system, it will create tasks and checks in their tables, but will have a policy_id set. I don't think the agent_id can be null, so I can use either a dummy agent_id {00000000-0000-0000-0000-000000000005} or set it to accept null values.
> 
> I haven't done too much with the alerts accept for creating some of the UI.
> 
> I should have some time to work on this over the next few weeks. Awesome work so far on this!

Nah don't worry your PR didn't break anything. I should have the tasks code added this weekend.
For the agent_id, why would it be null since a check or task has a foreign key to the Agent model, so you can get the agent_id using a reverse query.

Unless I'm not understanding correctly. Can you describe adding an example policy from start to finish and what tables will be created and/or updated?


> Also, I have been just rebasing my feature branches anytime you update you develop branch, so I am working off of the latest changes.
> 
> I'm not sure if my code broke the summary tab or not. I had to rework the salt container and I have that working now, but the wmi_detail module doesn't seem to be pulling any information. I ran the module manually on the agent and it is working. Maybe the return data is too large? I have the max_size set in the salt config. Or maybe this is a known issue? Other tasks are working so i wasn't sure. I have no experience with salt, but I'm learning!

As for the wmi_detail, first let me say amazing work on the docker part, I actually just got around to spinning up a new VPS in the cloud and testing docker.

Followed your instructions and it worked flawlessly. The few times I have played with docker I always had issues so I was very impressed when everything just worked lol! I'm definitely gonna have to start using docker more often it's awesome.

I then installed the agent on one of my windows laptops and the wmi_detail is working.

Doubt it's due to the return size as the value we set is 30MB which should be overkill for just json.

What operating system are you running the agent on?

Add `log_level: debug` to the top of api.conf in the salt folder then `tail -f /var/log/salt/master` from inside the container, then run this command on the windows agent from cmd:
`C:\salt\salt-call.bat system_info.system_info`
You should see what's happening in real time.
Also change the salt minion's log level from error to debug on the windows agent, in `C:\salt\conf\minion` then restart the salt-minion windows service and check the log file in `C:\salt\var\log\salt`

BTW I only noticed 1 thing not working on the docker setup, I am gonna create a separate issue now so we can discuss it there.

**Comment by wh1te909** [comment]
also just noticed salt master and api were running under python2 in docker. The minion uses python3 so that can cause issues. I changed docker to pull from the py3 repo instead of py2

**Pull request merged**
