### PR TITLE
Non root containers

### PR DESCRIPTION
**Pull request by joeldeteves**
This PR addresses #913 to make the docker environment more secure by running containers as non-root

With this change, all containers will run as non-root *except* for the Postgres and Init containers (Postgres container is not recommended for production and Init container is a run-once container that sets permissions on the volumes for all other containers).

I have tested on both docker-compose & K8s and it should work fine on both platforms

**Due to the nature of these changes, this may be a breaking change for some users. Therefore, I strongly recommend you test on an existing environment before merging these changes!!!**

Thank you,

### CODE REVIEW

**Comment by joeldeteves** [comment]
Hi guys, I've fixed the issue with the Redis container and added a few more fixes to make compatible with K8s (tested in both Docker & K8s).

All should be good to go now - goes without saying but please test before merging, thank you

**Comment by sadnub** [comment]
Your awesome! I will do some testing.

**Comment by joeldeteves** [comment]
Just pushed one more change @sadnub (quick cleanup of the volume inits + add a missing init for the certs volume; tested & worked in Docker on my side but please pull again if you didn't already see it).

Thanks,

**Comment by joeldeteves** [comment]
Per discussion with @wh1te909 - fixed the container ports on the `docker-compose` file to reflect the container port changes so please re-pull:

Old:
```
    ports:
      - "80:80"
      - "443:443"
```

New:

```
    ports:
      - "80:8080"
      - "443:4443"
```

Sorry guys - I checked to make sure the containers were running in Docker with no errors but i forgot to test local connectivity (we use K8s for our deployment so I forgot to test it the first time)

ICYMI, the reason for this change is because non-root users can't bind to ports under 1025 (does not affect external; docker takes care of the port forwarding so external HTTP / HTTP requests still come in on ports 80 / 443 respectively.

Let me know if any questions!

Thanks,

**Comment by joeldeteves** [comment]
Per conversation with @wh1te909 added a change to make sure `get_mesh_exe_url` prints the external url with port 443 instead of port 4443

**Review by wh1te909 — APPROVED** [review]
from my testing it looks good but will need @sadnub to sign off on it as well

**Review by sadnub — COMMENTED** [review]
Everything looks great! Thank you! I do have some questions on the tactical image entrypoint.sh

```
  touch /meshcentral-data/.initialized && chown -R 1000:1000 /meshcentral-data
  touch ${TACTICAL_DIR}/tmp/.initialized && chown -R 1000:1000 ${TACTICAL_DIR}
  touch ${TACTICAL_DIR}/certs/.initialized && chown -R 1000:1000 ${TACTICAL_DIR}/certs
  touch /mongo/data/db/.initialized && chown -R 1000:1000 /mongo/data/db
  touch /redis/data/.initialized && chown -R 1000:1000 /redis/data
```

What is the purpose of the above lines? I don't see them referenced anywhere else

**Comment by joeldeteves** [comment]
> What is the purpose of the above lines? I don't see them referenced anywhere else

The purpose of creating these files is to ensure the docker volumes are initialized by the init container and not by one of the other containers during startup.

This is so the permissions set by the init container persist when the volume gets mounted by the other containers.

It’s a workaround for the way docker-compose handles named volumes - we wouldn’t need to do this if we were using host mounted volumes.

Other than that they’re just empty files that serve no purpose once the init container has run.

**Comment by sadnub** [comment]
Cool that makes sense. I wonder what that will do when they upgrade from an old installation.

**Comment by wh1te909** [comment]
I did test a docker upgrade by first installing 0.11.3, docker-compose down, and then switching to this PR, build the images locally, and use the new docker-compose.yml and it appears to have worked without having to do anything else. but @sadnub if you could do this test as well just to make sure I didn't miss anything

**Pull request merged**
