### PR TITLE
added script for lenovo driver updates

### PR DESCRIPTION
**Pull request by MalteKiefer**

### CODE REVIEW

**Comment by silversword411** [comment]
You put the script in the wip...put it in `/scripts` if you're going to put it in the json or you'll get build errors.

**Comment by MalteKiefer** [comment]
thanks for the hint

**Comment by silversword411** [comment]
I think @wh1te909 broke the test with the demo site stuff ;)

I think you're good now it looks right.

**Comment by wh1te909** [comment]
yes i broke tests, formatting lol. it's good now thanks

**Pull request merged**
