### PR TITLE
Update update.sh

### PR DESCRIPTION
**Pull request by bradhawkins85**
Re-launch update.sh script after downloading new version

### CODE REVIEW

**Comment by wh1te909** [comment]
Hi thanks, not working on ubuntu 20:

```bash
tactical@rmmtest:~$ ./update.sh
Old update script detected, downloading and replacing with the latest version...
Script updated! Please re-run ./update.sh
./update.sh: line 20: update.sh: command not found
```

**Comment by bradhawkins85** [comment]
Hmm, weird, im on Ubunutu 20.04.2 LTS and got the same error but the script still ran and upgraded as expected.

tactical@tactical:~$ ./update.sh
Old update script detected, downloading and replacing with the latest version...
Script updated! Please re-run ./update.sh
./update.sh: line 20: update.sh: command not found
Hit:1 http://au.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://au.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://au.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]

**Comment by dinger1986** [comment]
I have a qupdate script that deletes the update script then downloads it again

**Comment by silversword411** [comment]
Is this the same issue where wget downloads a new file (and since it already exists changes the name)?

If you append -N to the wget it makes sure the existing files is replaced with the most recent, and avoids accidentally including old file(s).

See https://github.com/wh1te909/tacticalrmm/pull/324/files

**Comment by wh1te909** [comment]
ok I just used a different method here so doesn't throw any error https://github.com/wh1te909/tacticalrmm/commit/a297dc8b3b4a554de42a85322edae5d5c8684c4a

**Pull request closed without merging**
