### PR TITLE
Vulnerability fix

### PR DESCRIPTION
**Pull request by d4-maertzdorf**
Vulnerability fix django

### CODE REVIEW

**Comment by silversword411** [comment]
I almost added this a while ago but I didn't know enough of what I'm doing....thx for this! :)

Is there a way to run that analysis locally in your dev environment?

**Comment by d4-maertzdorf** [comment]
unsure.

I did find:
- DevSkim
https://github.com/Microsoft/DevSkim
This one seems to be able to intergrate with MS visual studio, not sure if it can be intergrated with all IDE's.

- CodeQL
https://help.semmle.com/lgtm-enterprise/user/help/running-queries-ide.html
This one seems to also work with visual studio code

**Review by d4-maertzdorf — COMMENTED** [review]
should work just fine

**Comment by silversword411** [comment]
We were just looking at the alerts...they were quite simplistic/wrong/irrelevant...got a good laugh though :D

Would be nice to find some better code scanners, that one was special. Nice to see we were running a tight ship!

**Comment by d4-maertzdorf** [comment]
Most definately, some results were "silly", and the code itself is "work in progress" the longer it is "in-place" the better the AI-learning on the backend can analyze if it is or is not something. (and 1st run usually will generate loads of "false positives".

**Pull request merged**
