### PR TITLE
Scripts update

### PR DESCRIPTION
**Pull request by tremor021**
Just added some explanations into scripts and added a new one

### CODE REVIEW

**Review by wh1te909 — CHANGES_REQUESTED** [review]
don't know why checks didn't catch it, ill fix but for now can you please add the new script to the `community_scripts.json` file plz follow the format and just add an entry for the new script you added

**Comment by tremor021** [comment]
Sorry, was late night, forgot to edit the json. Fixed now

**Comment by wh1te909** [comment]
checks are failing at duplicate guids, can you change the guid to something that's not already being used, can use https://www.uuidgenerator.net/or something

**Review by wh1te909 — CHANGES_REQUESTED** [review]
checks are failing at duplicate guids, can you change the guid to something that's not already being used, can use https://www.uuidgenerator.net/or something

**Review by wh1te909 — APPROVED** [review]
ty

**Pull request merged**
