### PR TITLE
Docs tweaks

### PR DESCRIPTION
**Pull request by silversword411**

### CODE REVIEW

**Comment by silversword411** [comment]
I don't think I did anything to break the checks, but not sure what to do.

**Comment by wh1te909** [comment]
no, coveralls is down lol https://status.coveralls.io/

**Comment by silversword411** [comment]
Must be hosted with voip.ms 😆

Getting some DDOS-lovin'

**Comment by silversword411** [comment]
Feel free to integrate PRs anytime you want. I always like sooner so I can sync official develop to my local so I know what I'm workin' with. 

Too much pending I forget I already fixed something ;)

**Pull request merged**
